package commands

import (
	"bufio"
	"fmt"
	"net"
	"os"
	"strings"

	"github.com/ParkWardRR/zelira/internal/engine"
	"github.com/spf13/cobra"
)

func init() {
	rootCmd.AddCommand(initCmd)
}

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Interactive wizard to generate config/.env",
	Long:  `Detect network interfaces, suggest IP ranges, and generate a config/.env file interactively.`,
	Run: func(cmd *cobra.Command, args []string) {
		reader := bufio.NewReader(os.Stdin)

		fmt.Println("Zelira Init")
		fmt.Println("═══════════")
		fmt.Println()

		// Detect interfaces
		ifaces := engine.ListInterfaces()
		fmt.Println("Detected network interfaces:")
		for i, name := range ifaces {
			addrs := getIfaceAddr(name)
			fmt.Printf("  %d) %s %s\n", i+1, name, addrs)
		}
		fmt.Println()

		iface := prompt(reader, "Network interface", first(ifaces))
		ip := prompt(reader, "Host static IP", detectIP(iface))
		gateway := prompt(reader, "Gateway IP", guessGateway(ip))
		subnet := prompt(reader, "Subnet (CIDR)", guessSubnet(ip))
		poolStart := prompt(reader, "DHCP pool start", guessPoolStart(ip))
		poolEnd := prompt(reader, "DHCP pool end", guessPoolEnd(ip))
		domain := prompt(reader, "Domain name", "home.local")
		tz := prompt(reader, "Timezone", detectTZ())
		password := prompt(reader, "Pi-hole admin password", "changeme")

		// Write .env
		envPath := findFile("config/")
		if envPath == "" {
			envPath = "config"
		}
		os.MkdirAll(envPath, 0755)
		outPath := envPath + "/.env"

		content := fmt.Sprintf(`# Zelira configuration — generated by zelira init
ZELIRA_IP=%s
ZELIRA_GATEWAY=%s
ZELIRA_SUBNET=%s
ZELIRA_POOL_START=%s
ZELIRA_POOL_END=%s
ZELIRA_DOMAIN=%s
ZELIRA_INTERFACE=%s
ZELIRA_TZ=%s
ZELIRA_PIHOLE_PASSWORD=%s
`, ip, gateway, subnet, poolStart, poolEnd, domain, iface, tz, password)

		if err := os.WriteFile(outPath, []byte(content), 0600); err != nil {
			fmt.Printf("Error writing %s: %v\n", outPath, err)
			os.Exit(1)
		}

		fmt.Printf("\n✓ Config written to %s\n", outPath)
		fmt.Println("Next: sudo zelira deploy")
	},
}

func prompt(reader *bufio.Reader, label, defaultVal string) string {
	if defaultVal != "" {
		fmt.Printf("  %s [%s]: ", label, defaultVal)
	} else {
		fmt.Printf("  %s: ", label)
	}
	input, _ := reader.ReadString('\n')
	input = strings.TrimSpace(input)
	if input == "" {
		return defaultVal
	}
	return input
}

func first(s []string) string {
	if len(s) > 0 {
		return s[0]
	}
	return "eth0"
}

func getIfaceAddr(name string) string {
	iface, err := net.InterfaceByName(name)
	if err != nil {
		return ""
	}
	addrs, _ := iface.Addrs()
	for _, a := range addrs {
		if ipnet, ok := a.(*net.IPNet); ok && ipnet.IP.To4() != nil {
			return fmt.Sprintf("(%s)", ipnet.IP.String())
		}
	}
	return ""
}

func detectIP(ifaceName string) string {
	iface, err := net.InterfaceByName(ifaceName)
	if err != nil {
		return "192.168.1.2"
	}
	addrs, _ := iface.Addrs()
	for _, a := range addrs {
		if ipnet, ok := a.(*net.IPNet); ok && ipnet.IP.To4() != nil {
			return ipnet.IP.String()
		}
	}
	return "192.168.1.2"
}

func guessGateway(ip string) string {
	parsed := net.ParseIP(ip).To4()
	if parsed == nil {
		return "192.168.1.1"
	}
	return fmt.Sprintf("%d.%d.%d.1", parsed[0], parsed[1], parsed[2])
}

func guessSubnet(ip string) string {
	parsed := net.ParseIP(ip).To4()
	if parsed == nil {
		return "192.168.1.0/24"
	}
	return fmt.Sprintf("%d.%d.%d.0/24", parsed[0], parsed[1], parsed[2])
}

func guessPoolStart(ip string) string {
	parsed := net.ParseIP(ip).To4()
	if parsed == nil {
		return "192.168.1.100"
	}
	return fmt.Sprintf("%d.%d.%d.100", parsed[0], parsed[1], parsed[2])
}

func guessPoolEnd(ip string) string {
	parsed := net.ParseIP(ip).To4()
	if parsed == nil {
		return "192.168.1.250"
	}
	return fmt.Sprintf("%d.%d.%d.250", parsed[0], parsed[1], parsed[2])
}

func detectTZ() string {
	// Try /etc/timezone first
	if data, err := os.ReadFile("/etc/timezone"); err == nil {
		return strings.TrimSpace(string(data))
	}
	// Try timedatectl
	if link, err := os.Readlink("/etc/localtime"); err == nil {
		parts := strings.SplitAfter(link, "zoneinfo/")
		if len(parts) == 2 {
			return parts[1]
		}
	}
	return "America/New_York"
}
